site_name: Lucretia Field - MDEF
site_url: https://mydomain.org/mysite
site_description: Master in Design for Emergent Futures
# copyright: Copyleft 2024 "Lucretia Field" - GNU Free Documentation License
# repo_name: 'LKField : mdef'
# site_url: hhttps://lkfield.github.io/mdef/
# repo_url: https://github.com/LKField/mdef

nav:
  - Home: index.md
  - About: about/me.md
  - Term 1:
      - Landing: term1/landing.md
      - Design Studio 01: term1/design.md


theme:
  name: material
    # custom_dir: overrides
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer

  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto
    code: Roboto Mono

# Add functionality from ttps://squidfunk.github.io/mkdocs-material
markdown_extensions:
  - attr_list
  # for emojis https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    #  for code blocks https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    #  pygments list https://pygments.org/languages/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # # for admonitions https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=adm
  - admonition
  - pymdownx.details

copyright: Copyleft 2024 "Lucretia Field" - GNU Free Documentation License
